# Generated by Django 4.1.13 on 2024-05-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('product_type', models.CharField(max_length=50)),
                ('product_id', models.IntegerField()),
                ('content', models.CharField(max_length=8200)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
