# Generated by Django 4.1.13 on 2024-05-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='Type',
            new_name='type',
        ),
    ]
