# Generated by Django 4.1.13 on 2024-05-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_rename_type_mobile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
