# Generated by Django 4.1.13 on 2024-05-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=10)),
                ('order_id', models.CharField(max_length=10)),
                ('payment_id', models.CharField(max_length=10)),
                ('status', models.CharField(default='Ready to dispatch', max_length=50)),
            ],
            options={
                'db_table': 'shipments',
            },
        ),
    ]
