# Generated by Django 4.1.13 on 2024-05-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=10)),
                ('product_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
