# Generated by Django 4.1.13 on 2024-05-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_status',
            field=models.BooleanField(default=False),
        ),
    ]
