# Generated by Django 4.1.13 on 2024-05-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='ward',
            field=models.CharField(max_length=50),
        ),
    ]
