# Generated by Django 4.1.13 on 2024-05-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_registration',
            table='users',
        ),
    ]
