# Generated by Django 4.1.13 on 2024-05-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0003_alter_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
