# Generated by Django 4.1.13 on 2024-05-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('product_type', models.CharField(max_length=50)),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
    ]
