# Generated by Django 4.1.13 on 2024-05-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
