# Generated by Django 4.1.13 on 2024-05-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
